"""varoascii effects module."""

from varoascii.effects.effect_ascii import Ascii
from varoascii.effects.effect_beams import Beams
from varoascii.effects.effect_binarypath import BinaryPath
from varoascii.effects.effect_blackhole import Blackhole
from varoascii.effects.effect_bouncyballs import BouncyBalls
from varoascii.effects.effect_bubbles import Bubbles
from varoascii.effects.effect_burn import Burn
from varoascii.effects.effect_cinema import Cinema
from varoascii.effects.effect_colorshift import ColorShift
from varoascii.effects.effect_crumble import Crumble
from varoascii.effects.effect_decrypt import Decrypt
from varoascii.effects.effect_errorcorrect import ErrorCorrect
from varoascii.effects.effect_expand import Expand
from varoascii.effects.effect_fireworks import Fireworks
from varoascii.effects.effect_glitch import Glitch
from varoascii.effects.effect_hack import Hack
from varoascii.effects.effect_highlight import Highlight
from varoascii.effects.effect_laseretch import LaserEtch
from varoascii.effects.effect_matrix import Matrix
from varoascii.effects.effect_middleout import MiddleOut
from varoascii.effects.effect_neon import Neon
from varoascii.effects.effect_orbittingvolley import OrbittingVolley
from varoascii.effects.effect_overflow import Overflow
from varoascii.effects.effect_pour import Pour
from varoascii.effects.effect_print import Print
from varoascii.effects.effect_radar import Radar
from varoascii.effects.effect_rain import Rain
from varoascii.effects.effect_random_sequence import RandomSequence
from varoascii.effects.effect_rings import Rings
from varoascii.effects.effect_scattered import Scattered
from varoascii.effects.effect_slice import Slice
from varoascii.effects.effect_slide import Slide
from varoascii.effects.effect_smoke import Smoke
from varoascii.effects.effect_spotlights import Spotlights
from varoascii.effects.effect_spray import Spray
from varoascii.effects.effect_swarm import Swarm
from varoascii.effects.effect_sweep import Sweep
from varoascii.effects.effect_synthgrid import SynthGrid
from varoascii.effects.effect_thunderstorm import Thunderstorm
from varoascii.effects.effect_typewriter import Typewriter
from varoascii.effects.effect_unstable import Unstable
from varoascii.effects.effect_vhstape import VHSTape
from varoascii.effects.effect_waves import Waves
from varoascii.effects.effect_wipe import Wipe
